blueprint:
  name: Lutron Aurora dimmer control for light group
  description: >
    Uses MQTT messages from Zigbee2MQTT for a Lutron Aurora dimmer
    to control a light or light group using the Home Assistant automation system.
    Smooth transitions are applied when adjusting brightness (levels 1–254),
    while 0 = off and 255 = full brightness without transition.
  domain: automation
  input:
    mqtt_topic:
      name: MQTT Topic
      description: >
        Full Zigbee2MQTT topic for the Aurora device,
        e.g. 'zigbee2mqtt/Basement Lights Switch'
      selector:
        text:

    target_light:
      name: Light or Light Group
      description: The light or light group to control
      selector:
        target:
          entity:
            domain: light

    transition_duration:
      name: Transition Duration (in seconds)
      description: >
        Transition time to use when changing brightness levels (1–254).
        Ignored for full on/off.
      default: 1.0
      selector:
        number:
          min: 0
          max: 5
          step: 0.1
          unit_of_measurement: seconds
          mode: slider

mode: queued
max_exceeded: silent

trigger:
  - platform: mqtt
    topic: !input mqtt_topic
    payload: brightness_move_to_level
    value_template: "{{ value_json.action }}"

variables:
  action: "{{ trigger.payload_json.action }}"
  action_level: "{{ trigger.payload_json.action_level | int(0) }}"
  transition_time: !input transition_duration

action:
  - choose:
      # CASE 1: Turn off when brightness is 0
      - conditions:
          - condition: template
            value_template: "{{ action_level == 0 }}"
        sequence:
          - service: light.turn_off
            target: !input target_light

      # CASE 2: Turn on full brightness when level is 255
      - conditions:
          - condition: template
            value_template: "{{ action_level == 255 }}"
        sequence:
          - service: light.turn_on
            target: !input target_light
            data:
              brightness: 255

    # CASE 3: Smooth brightness adjustment
    default:
      - service: light.turn_on
        target: !input target_light
        data:
          brightness: "{{ action_level }}"
          transition: "{{ transition_time }}"
